# ----------- CONFIGURABLE START -----------
title:            "张丛静"
description:      "A Coder"
url:              https://vmrss.github.io 
signoff:          "张丛静" 
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
timezone:         Asia/Shanghai

links:
  - name:         Posts
    url:          /
    external:     false
  - name:         RSS
    url:          /feed.xml
  - name:         About
    url:          /about
# ------------ CONFIGURABLE END ------------

permalink:        /:title
defaults:
  - values:
      layout: "default"
